/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or unnecessarily formatted.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CalcularImport } from './routes/calcular'
import { Route as ThreeDImport } from './routes/3d'
import { Route as GrahasSlugImport } from './routes/grahas.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CalcularRoute = CalcularImport.update({
  path: '/calcular',
  getParentRoute: () => rootRoute,
} as any)

const ThreeDRoute = ThreeDImport.update({
  path: '/3d',
  getParentRoute: () => rootRoute,
} as any)

const GrahasSlugRoute = GrahasSlugImport.update({
  path: '/grahas/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/calcular': {
      preLoaderRoute: typeof CalcularImport
      parentRoute: typeof rootRoute
    }
    '/3d': {
      preLoaderRoute: typeof ThreeDImport
      parentRoute: typeof rootRoute
    }
    '/grahas/$slug': {
      preLoaderRoute: typeof GrahasSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CalcularRoute,
  ThreeDRoute,
  GrahasSlugRoute,
])
